### ISSUE TITLE
Python 3.12

### ISSUE THREAD

**Issue by yarikoptic** [jayvdb/nose3#5]
thanks for maintaining this fork. Let me know if you need help

tried with 3.12 on AnnexRemote which is still nose

```
❯ python -m nose -s -v tests
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "/home/yoh/proj/misc/AnnexRemote/venvs/dev3.12/lib/python3.12/site-packages/nose/__init__.py", line 1, in <module>
    from nose.core import collector, main, run, run_exit, runmodule
  File "/home/yoh/proj/misc/AnnexRemote/venvs/dev3.12/lib/python3.12/site-packages/nose/core.py", line 12, in <module>
    from nose.loader import defaultTestLoader
  File "/home/yoh/proj/misc/AnnexRemote/venvs/dev3.12/lib/python3.12/site-packages/nose/loader.py", line 21, in <module>
    from nose.importer import Importer, add_path, remove_path
  File "/home/yoh/proj/misc/AnnexRemote/venvs/dev3.12/lib/python3.12/site-packages/nose/importer.py", line 12, in <module>
    from imp import find_module, load_module, acquire_lock, release_lock
ModuleNotFoundError: No module named 'imp'
```

**Comment by jayvdb** [comment]
Sadly we have failures on py311 also: https://github.com/jayvdb/nose3/issues/2

You may find that https://github.com/mdmintz/pynose is better maintained.  It appears to work on py312
